/**
 * Force-directed graph renderer.
 * Called by renderVis() in main.js when force-directed mode is selected.
 * Calls bindTooltips() from tooltip.js after drawing.
 * 
 * @author Ellora Devulapally, Taft Harrell
 */

/**
 * Enables the dragging of nodes by user. Generated by ChatGPT.
 * 
 * @param {*} simulation 
 * @returns drag event
 */
function drag(simulation) {
    function dragstarted(event, d) {
        if (!event.active) simulation.alphaTarget(0.3).restart();
        d.fx = d.x;
        d.fy = d.y;
    }
    function dragged(event, d) {
        d.fx = event.x;
        d.fy = event.y;
    }
    function dragended(event, d) {
        if (!event.active) simulation.alphaTarget(0);
        d.fx = null;
        d.fy = null;
    }
    return d3.drag()
        .on("start", dragstarted)
        .on("drag", dragged)
        .on("end", dragended);
}

/**
 * Creates nodes and links and draws onto SVG using force-directed layout. 
 * Handles drag physics.
 */
function renderForceDirectedVis() {
    let vis = this;

    // Determine which nodes to show for the current phase
    let visibleNodes = vis.nodes.filter(n => vis.phaseNodes.has(n.id));

    // List of arrow types --> normal use for copying data for physics simulation 
    const types = ["basic"];

    // Create copies of all links
    const links = [];
    for (let i = 0; i < vis.links.length; i++) {
        const originalLink = vis.links[i];
        const linkCopy = Object.create(originalLink);
        links.push(linkCopy);
    }

    // Create copies of all nodes
    const nodes = [];
    for (let i = 0; i < visibleNodes.length; i++) {
        const originalNode = visibleNodes[i];
        const nodeCopy = Object.create(originalNode);
        nodes.push(nodeCopy);
    }

    //Define width and height of SVG, as well as a few drawing and physics constants
    const width = 700;
    const height = 550;
    const nodeRadius = 10;
    var collisionForce = (100 - Math.floor(nodes.length)) / 1.5;
    if(collisionForce < 30) {
        collisionForce = 30;
    }
    const collisionStrength = -100;

    // Clear and rebuild the SVG on every render
    d3.select("#chart-area").select("svg").remove();

    const simulation = d3.forceSimulation(nodes)
        .force("link", d3.forceLink(links).id(d => d.id))
        .force("charge", d3.forceManyBody().strength(collisionStrength))
        .force("x", d3.forceX())
        .force("y", d3.forceY())
        .force('collide', d3.forceCollide(d => collisionForce));
    
    const svg = d3.select("#chart-area")
        .append("svg")
        .attr("id", "SVG")
        .attr("width", width * 1.5)
        .attr("height", height * 1.5)
        .attr("viewBox", [-width / 2, -height / 2, width, height]);

    // Per-type markers, as they don't inherit styles.
    svg.append("defs").selectAll("marker")
        .data(types)
        .join("marker")
        .attr("id", d => `arrow-${d}`)
        .attr("viewBox", "0 -5 10 10")
        .attr("refX", 20)
        .attr("refY", 0)
        .attr("markerWidth", 6)
        .attr("markerHeight", 6)
        .attr("orient", "auto")
        .append("path")
        .attr("fill", "black")
        .attr("d", 'M0,-5L10,0L0,5');

    const link = svg.append("g")
        .attr("fill", "none")
        .attr("stroke-width", 1.5)
        .selectAll("path")
        .data(links)
        .join("path")
        .attr("class", "edge")
        .attr("stroke", "black")
        .attr("marker-end", d => `url(${new URL(`#arrow-${d.type}`, location)})`);

    const node = svg.append("g")
        .attr("fill", "currentColor")
        .attr("stroke-linecap", "round")
        .attr("stroke-linejoin", "round")
        .selectAll("g")
        .data(nodes)
        .join("g")
        .call(drag(simulation));

    node.append("circle")
        .attr("class", "node")
        .attr("stroke", "white")
        .attr("stroke-width", 1.5)
        .attr("r", nodeRadius)
        .attr('fill', d => '#6baed6');

    node.append("text")
        .attr("x", 10)
        .attr("y", "0.31em")
        .text(d => d.id)
        .clone(true).lower()
        .attr("fill", "none");

    node.on('dblclick', (e, d) => console.log(nodes[d.index]));

    simulation.on("tick", () => {
        link.attr("d", d => `M${d.source.x},${d.source.y}A0,0 0 0,1 ${d.target.x},${d.target.y}`);
        node.attr("transform", d => `translate(${d.x},${d.y})`);
    });

    // Store on vis so tooltip.js can bind hover handlers to these elements
    vis.nodeSelection = node;
    vis.linkSelection = link;

    bindTooltips();  // tooltip.js
}